# Faça um arquivo que suba um container de docker run -it --rm --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:4.0-management

version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:4.0-management
    ports:
      - "5672:5672"
      - "15672:15672"
    container_name: rabbitmq
    restart: always

# Para subir o container, basta rodar o comando docker-compose up -d